[package]
name = "misra-rust"
version = "0.1.0"
authors = ["Shea Newton <snewton@polysync.io>"]

[dependencies.clippy]
version = "=0.0.180"

[dependencies.custom_lints]
path = "./custom_lints"

[dev-dependencies.compiletest_rs]
version = "=0.3.5"

